services:
    # nginx
    web:
        image: nginx:latest
        # container_name: wempsrv
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

    # php
    app:
        build:
            dockerfile: ./php/Dockerfile

    # mysql
    sql:
        image: mysql:8.2
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: docker-php

volumes:
    mysqldata:
